FROM ubuntu:18.04
MAINTAINER BeMg

RUN apt-get update && apt-get install -y git autoconf automake autotools-dev curl libmpc-dev libmpfr-dev libgmp-dev libusb-1.0-0-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev device-tree-compiler pkg-config libexpat-dev
RUN git clone https://github.com/riscv/riscv-tools.git && mkdir risc-v
ENV RISCV /risc-v
RUN cd riscv-tools && \
    git submodule update --init --recursive && \
    curl https://gist.githubusercontent.com/BeMg/6cb6f7168e3dab287614e17862cc1fba/raw/5b78a3bd269b95696d57ac48e2743a656c90848a/build.common > build.common && \
    ./build.sh
RUN rm -rf riscv-isa-sim riscv-opcodes riscv-gnu-toolchain/riscv-binutils-gdb && \
    git clone git@github.com:BeMg/riscv-isa-sim.git && git clone git@github.com:BeMg/riscv-opcodes.git && \
    cd riscv-gnu-toolchain && git clone git@github.com:BeMg/riscv-binutils-gdb.git && cd .. && \
    cd riscv-isa-sim/build && make -j32 && make install -j32 && cd ../.. && \
    cd riscv-gnu-toolchain/riscv-binutils-gdb && ./configure --target=riscv64-unknown-elf --prefix=RISCV && make -j32 && make install && cd ../.. \
    cd / && rm -rf riscv-tools && echo "export PATH=$PATH:/risc-v/bin" >> ~/.bashrc