FROM ubuntu:18.04
MAINTAINER BeMg

RUN apt-get update && apt-get install -y git autoconf automake autotools-dev curl libmpc-dev libmpfr-dev libgmp-dev libusb-1.0-0-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev device-tree-compiler pkg-config libexpat-dev
RUN mkdir risc-v && git clone --recursive https://github.com/riscv/riscv-gnu-toolchain && cd riscv-gnu-toolchain && ./configure --prefix=$RISCV && make -j2 && make install -j2 && rm -rf riscv-bintuils && git clone https://github.com/BeMg/riscv-bintuils.git && cd riscv-binutils && ./configure --prefix=$RISCV --target=riscv64-unknown-elf && make -j2 && make install -j3
ENV RISCV /risc-v
RUN git clone https://github.com/riscv/riscv-tools.git 
RUN cd riscv-tools && git submodule update riscv-pk && rm -rf riscv-isa-sim && git clone https://github.com/BeMg/riscv-isa-sim.git && ./build-spike-pk.sh && cd / && rm -rf riscv-tools && echo "export PATH=$PATH:/risc-v/bin" >> ~/.bashrc