FROM ubuntu:18.04
MAINTAINER BeMg

RUN apt-get update && apt-get install -y git autoconf automake autotools-dev curl libmpc-dev libmpfr-dev libgmp-dev libusb-1.0-0-dev gawk \
 build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev device-tree-compiler pkg-config libexpat-dev && mkdir risc-v
ENV RISCV /risc-v
RUN git clone --recursive https://github.com/riscv/riscv-gnu-toolchain && \
    cd riscv-gnu-toolchain && ./configure --prefix=$RISCV && make -j4 && \
    rm -rf riscv-binutils && git clone https://github.com/BeMg/riscv-bintuils.git riscv-binutils && \
    cd riscv-binutils && ./configure --prefix=$RISCV --target=riscv64-unknown-elf && make -j4 && make install -j4
RUN git clone https://github.com/riscv/riscv-tools.git 
RUN cd riscv-tools && git submodule update --init riscv-pk && git submodule update --init riscv-fesvr && rm -rf riscv-isa-sim && git clone https://github.com/BeMg/riscv-isa-sim.git && \
     ./build-spike-pk.sh && echo "export PATH=$PATH:/risc-v/bin" >> ~/.bashrc