FROM ubuntu:18.04
MAINTAINER BeMg

RUN apt-get update && apt-get install -y git autoconf python3 python3-dev python3-pip python3-setuptools gcc libtinfo-dev zlib1g-dev build-essential cmake \
    automake autotools-dev curl wget libmpc-dev libmpfr-dev libgmp-dev libusb-1.0-0-dev gawk \
    build-essential bison flex device-tree-compiler texinfo gperf libtool patchutils bc zlib1g-dev device-tree-compiler pkg-config libexpat-dev && mkdir risc-v
RUN pip3 install requests tqdm numpy 
ENV RISCV /risc-v
RUN cd ~ && wget https://raw.githubusercontent.com/chentinghao/download_google_drive/master/download_gdrive.py && \
    python3 download_gdrive.py 1pPhHP6vVE6t9xBj8DHuUIU9DD8G0amEs ~/riscv_toolchain.tar
RUN cd ~ && tar -vxf riscv_toolchain.tar && rm riscv_toolchain.tar
RUN cd ~ && cd riscv-gnu-toolchain && ./configure --prefix=$RISCV --with-arch=rv64gcv --with-abi=lp64 && make -j6
ENV PATH="/risc-v/bin:${PATH}"
RUN cd ~ && git clone https://github.com/riscv/riscv-pk.git && \
    cd riscv-pk && mkdir build && cd build && \
    ../configure --prefix=$RISCV --host=riscv64-unknown-elf && \
    make -j4 && make install -j4
RUN cd ~ && git clone https://github.com/riscv/riscv-isa-sim.git && \
    cd riscv-isa-sim && mkdir build && cd build && \
    ../configure --prefix=$RISCV && make -j4 && make install -j6
RUN cd ~ && mkdir llvm9 && cd llvm9 && python3 ~/download_gdrive.py 1VVEgpUiVIqQChbW6drkOOPdQmr1czjhJ ./llvm.tar && tar -vxf llvm.tar && mkdir build
RUN cd ~ && cd ./llvm9/build && cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE="Debug" \
  -DBUILD_SHARED_LIBS=True -DLLVM_USE_SPLIT_DWARF=True \
  -DLLVM_TARGETS_TO_BUILD="RISCV" \
  -DLLVM_OPTIMIZED_TABLEGEN=True \
  -DLLVM_BUILD_TESTS=True \
  -DDEFAULT_SYSROOT=$RISCV/riscv64-unknown-elf \
  -DGCC_INSTALL_PREFIX=$RISCV \
  -DLLVM_DEFAULT_TARGET_TRIPLE="riscv64-unknown-elf" \
  -DCMAKE_INSTALL_PREFIX=../install \
  ../llvm && make -j8
ENV PATH="~/llvm9/build/bin:${PATH}"
